treatments:
  - name: basic
    factorIds:
      - jTXNCATMbGyw2uo9J
      - no4NocAjd3Ny7cpxX
      - Q7bKTC87PQNjfNfmn
      - zfz7GdhAfKb3K5vRm
factorTypes:
  - _id: jTXNCATMbGyw2uo9J
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: ZRZ6Cj3NziZauB3bA
    name: roundCount
    description: Number of rounds played
    required: false
    type: Integer
    min: 1
    max: 100
  - _id: Jroupzjefq85xtNGj
    name: stageLength
    description: Number of seconds in stage
    required: false
    type: Integer
    min: 1
    max: 12000
  - _id: 4q2RSFfsrB3oFRTu6
    name: botsCount
    description: Number of bots
    required: false
    type: Integer
    min: 0
    max: 100
factors:
  - _id: x8NsYrN2aEXJ9ns8k
    name: one
    value: 1
    factorTypeId: jTXNCATMbGyw2uo9J
  - _id: fXPTZpBnxsxuotxh6
    name: four
    value: 4
    factorTypeId: jTXNCATMbGyw2uo9J
  - _id: stSByaLq2axRCzySD
    name: one
    value: 1
    factorTypeId: ZRZ6Cj3NziZauB3bA
  - _id: no4NocAjd3Ny7cpxX
    name: three
    value: 3
    factorTypeId: ZRZ6Cj3NziZauB3bA
  - _id: Q7bKTC87PQNjfNfmn
    name: normal
    value: 120
    factorTypeId: Jroupzjefq85xtNGj
  - _id: sCsrr2mz5qdeCGS4T
    name: long
    value: 12000
    factorTypeId: Jroupzjefq85xtNGj
  - _id: 2zkyc3vkB5t4umaR7
    name: one
    value: 1
    factorTypeId: 4q2RSFfsrB3oFRTu6
  - _id: zfz7GdhAfKb3K5vRm
    name: three
    value: 3
    factorTypeId: 4q2RSFfsrB3oFRTu6
lobbyConfigs:
  - name: long
    timeoutType: lobby
    timeoutInSeconds: 12000
    timeoutStrategy: fail
    gameLobbyIds: []
